name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
env:
  DOTNET_NOLOGO: true
jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            name: Linux
      fail-fast: false
    steps:
      - name: Checkout
        if: github.event_name != 'pull_request_target'
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Checkout for Dependabot
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v2.4.0
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
          fetch-depth: 0   
      - name: Setup .NET 5 
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: 5.0.x          
      - name: Setup .NET Core 3.1 
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: 3.1.x   
      - name: Build
        run: dotnet build src --configuration Release
      - name: Upload packages
        if: matrix.name == 'Windows'
        uses: actions/upload-artifact@v2.2.4
        with:
          name: NuGet packages
          path: nugets/
          retention-days: 7    
      - name: Setup Oracle 
        if: matrix.name == 'Linux'
        shell: bash
        run: |
          docker run -d -p 1521:1521 -e ORACLE_PASSWORD=Welcome1 container-registry.oracle.com/database/express:latest
          echo "OracleConnectionString=Data Source=(DESCRIPTION=(ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = 127.0.0.1)(PORT = 1521)))(CONNECT_DATA = (SERVER = DEDICATED)(SERVICE_NAME = XE)));User Id=SYSTEM; Password=Welcome1; Enlist=dynamic" >> $GITHUB_ENV
          sleep 20
      - name: Run tests
        uses: Particular/run-tests-action@v1.0.0
